apiVersion: apps/v1
kind: Deployment
metadata:
  name: krakend
  namespace: krakend
spec:
  selector:
    matchLabels:
      app: krakend
  replicas: 2
  template:
    metadata:
      labels:
        app: krakend
    spec:
      containers:
      - name: krakend
        ports:
        - containerPort: 8080
        image: 246958245973.dkr.ecr.eu-west-2.amazonaws.com/krakend-enterprise:0.0.21
        command: [ "/usr/bin/krakend-ee" ]
        args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "--accept-eula" , "-p", "8080" ]
        env:
        - name: KRAKEND_PORT
          value: "8080"
