apiVersion: v1
kind: Service
metadata:
  name: krakend
  namespace: krakend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8080
    protocol: TCP
  selector:
    app: krakend
---
apiVersion: v1
kind: Service
metadata:
  name: krakend-stats
  namespace: krakend
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8090
    protocol: TCP
  selector:
    app: krakend
